### ISSUE TITLE
server not found

### ISSUE THREAD

**Issue by canbera** [steeven-th/pterodactyl-status-server-wordpress#2]
i dont know if i did something wrong, but it seemed as if the plugin took well to adding my keys and IP
but it threw a hissy fit when i tried to add servers
![image](https://github.com/steeven-th/pterodactyl-status-server-wordpress/assets/140513541/c11954ca-0711-4897-9e3d-4c03e666de1a)

**Comment by steeven-th** [comment]
Can you test by replacing the IP with the domain name in configuration ?

**Comment by RememberShephard** [comment]
I can confirm that adding your domain name rather than IP works.
